-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Aug 03, 2018 at 03:30 PM
-- Server version: 5.5.53-0ubuntu0.14.04.1
-- PHP Version: 7.2.8-1+ubuntu14.04.1+deb.sury.org+1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `larascrap`
--

-- --------------------------------------------------------

--
-- Table structure for table `jobs`
--

CREATE TABLE IF NOT EXISTS `jobs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `queue` varchar(161) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `attempts` tinyint(3) unsigned NOT NULL,
  `reserved_at` int(10) unsigned DEFAULT NULL,
  `available_at` int(10) unsigned NOT NULL,
  `created_at` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `jobs_queue_reserved_at_index` (`queue`,`reserved_at`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=121 ;

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(161) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=29 ;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(25, '2014_10_12_000000_create_users_table', 1),
(26, '2014_10_12_100000_create_password_resets_table', 1),
(27, '2018_08_03_062811_create_scrapdatas_table', 1),
(28, '2018_08_03_070917_create_jobs_table', 1);

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` varchar(161) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(161) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `scrapdatas`
--

CREATE TABLE IF NOT EXISTS `scrapdatas` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(161) COLLATE utf8mb4_unicode_ci NOT NULL,
  `related_url` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL,
  `img_url` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL,
  `related_details` longtext COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=121 ;

--
-- Dumping data for table `scrapdatas`
--

INSERT INTO `scrapdatas` (`id`, `name`, `related_url`, `img_url`, `related_details`, `created_at`, `updated_at`) VALUES
(1, 'Batman (2016-)', 'http://readcomicsonline.ru/comic/batman-2016', 'http://readcomicsonline.ru/uploads/manga/batman-2016/cover/cover_thumb.jpg', '[{"raiting":"4.45"},{"summary":"\\"I AM GOTHAM\\" Chapter One\\r\\n\\r\\nNo one has ever stopped the Caped Crusader. Not The Joker. Not Two-Face. Not even the entire Justice League. But how does Batman confront a new hero who wants to save the city from the Dark Knight?\\r\\n\\r\\nCAN''T MISS: Superstar artist David Finch returns to Batman alongside writer Tom King for this five-part storyline."}]', '2018-08-03 04:10:19', '2018-08-03 04:10:23'),
(2, 'Injustice 2 (2017-)', 'http://readcomicsonline.ru/comic/injustice-2-2017', 'http://readcomicsonline.ru/uploads/manga/injustice-2-2017/cover/cover_thumb.jpg', '[{"raiting":"4.33"},{"summary":"The all-new prequel to the highly anticipated Injustice 2 video game begins here! Original INJUSTICE writer Tom Taylor continues the story from the hit series INJUSTICE: GODS AMONG US. Superman is imprisoned, and it\\u2019s up to Batman to put the world back together. But with Superman\\u2019s iron-fisted regime eliminated, other forces rise up to fill the void. And Batman doesn\\u2019t have a lot of allies left to help stop them."}]', '2018-08-03 04:10:20', '2018-08-03 04:10:23'),
(3, 'The Flash (2016-)', 'http://readcomicsonline.ru/comic/the-flash-2016', 'http://readcomicsonline.ru/uploads/manga/the-flash-2016/cover/cover_thumb.jpg', '[{"raiting":"4.52"},{"summary":"\\"LIGHTNING STRIKES TWICE\\" Chapter One\\r\\n\\r\\nA new storm brews over Central City and disproves the old adage about lightning never, well...you know. Just as Barry begins to feel overwhelmed fighting crime, a new speedster debuts\\u2014but just where did this amazing new friend come from?\\r\\n\\r\\nFLASH FACT: \\"2016 is the 60th anniversary of Barry Allen becoming The Flash, and it''s a privilege to be a part of it,\\" says writer Joshua Williamson. \\"''The Return of Barry Allen'' in FLASH #79 [1993] is one of my favorite comics of all time. It''s where I became a Flash fan for life.\\""}]', '2018-08-03 04:10:20', '2018-08-03 04:10:24'),
(4, 'Darth Vader (2017-)', 'http://readcomicsonline.ru/comic/darth-vader-2017', 'http://readcomicsonline.ru/uploads/manga/darth-vader-2017/cover/cover_thumb.jpg', '[{"raiting":"4.74"},{"summary":"The most fearsome villain of all time returns with an all-new series! When Anakin Skywalker fell, both to the pull of the dark side and to the blade of Obi-Wan Kenobi, he rose back up, more machine than man. Having lost everything that was once dear to him, the former chosen one must take his first steps into a darker world\\u2026as Darth Vader, Dark Lord of the Sith!"}]', '2018-08-03 04:10:20', '2018-08-03 04:10:25'),
(5, 'Justice League (2016-)', 'http://readcomicsonline.ru/comic/justice-league-2016', 'http://readcomicsonline.ru/uploads/manga/justice-league-2016/cover/cover_thumb.jpg', '[{"raiting":"3.88"},{"summary":"\\"THE EXTINCTION MACHINE\\" Chapter One \\r\\n\\r\\nThe oceans rise. The earth quakes. And an ancient power rises to reclaim not just the world, but the universe itself\\u2014and not even the combined might of the Justice League can stop it. An all-new era begins with this epic by comic book legend Bryan Hitch (JLA, The Ultimates) and master storyteller Tony S. Daniel (BATMAN: R.I.P., DEATHSTROKE)."}]', '2018-08-03 04:10:20', '2018-08-03 04:10:25'),
(6, 'The Amazing Spider-Man (2015-)', 'http://readcomicsonline.ru/comic/the-amazing-spiderman-2015', 'http://readcomicsonline.ru/uploads/manga/the-amazing-spiderman-2015/cover/cover_thumb.jpg', '[{"raiting":"4.5"},{"summary":"Volume 4.\\r\\n\\r\\nSpider-Man has gone global! Parker Industries is more successful than ever, with offices in New York, Shanghai, London and San Francisco and Peter Parker is racking up the frequent flyer miles with his \\"bodyguard\\" Spider-Man in tow, of course. But success breeds enemies and a reinvigorated Zodiac have also widened their scope to threaten the whole world. Join Dan Slott and Giuseppe Camuncoli as they take Spider-Man to the next level! This huge first issue also includes stories featuring Silk, Spidey 2099, and much more!"}]', '2018-08-03 04:10:20', '2018-08-03 04:10:26'),
(7, 'Dark Nights: Metal (2017-)', 'http://readcomicsonline.ru/comic/dark-nights-metal-2017', 'http://readcomicsonline.ru/uploads/manga/dark-nights-metal-2017/cover/cover_thumb.jpg', '[{"raiting":"4.59"},{"summary":"The superstar BATMAN team of writer Scott Snyder and artist Greg Capullo reunite for a massive, universe-spanning event! \\r\\n\\r\\nDARK NIGHTS: THE FORGE and THE CASTING hinted at dark corners of reality that have never been seen till now! Now, as DARK DAYS: METAL begins, the Dark Multiverse is revealed in all its devastating danger-and the threats it contains are coming for the DC Universe!\\r\\n\\r\\nDARK DAYS: METAL is a DC event unlike any other-one that will push Batman, Superman and heroes of the Justice League beyond their limits to take on threats unlike any our world has ever seen! It will take the combined might of the World''s Greatest Heroes as you''ve never seen them before to face what''s coming their way!"}]', '2018-08-03 04:10:20', '2018-08-03 04:10:27'),
(8, 'Superman (2016-)', 'http://readcomicsonline.ru/comic/superman-2016', 'http://readcomicsonline.ru/uploads/manga/superman-2016/cover/cover_thumb.jpg', '[{"raiting":"4.49"},{"summary":"\\"THE SON OF SUPERMAN\\" Chapter One\\r\\n\\r\\nThe Last Son of Krypton must decide whether to help his young son use his new and rapidly increasing abilities, or hide them from the world.\\r\\n\\r\\nTHE CREATORS: The team supreme that brought fans the adventures of Damian Wayne in BATMAN AND ROBIN returns for the adventures of Superman and his offspring."}]', '2018-08-03 04:10:20', '2018-08-03 04:10:27'),
(9, 'The Walking Dead (2003-)', 'http://readcomicsonline.ru/comic/the-walking-dead-2003', 'http://readcomicsonline.ru/uploads/manga/the-walking-dead-2003/cover/cover_thumb.jpg', '[{"raiting":"4.73"},{"summary":"An epidemic of apocalyptic proportions has swept the globe, causing the dead to rise and feed on the living. In a matter of months, society has crumbled; there is no government, no grocery stores, no mail delivery, no cable TV.\\r\\n\\r\\nRick Grimes finds himself one of the few survivors in this terrifying world. He was a small town cop who had only fired his weapon a couple times but never at anyone and had only ever seen one dead body. Separated from his family, he must sort through the death and horror to try and find his wife and son. In a world ruled by the dead, people are forced to finally begin living. Issue #1 - 159 can be downloaded at : http:\\/\\/getcomics.info\\/other-comics\\/the-walking-dead-comics-1-138-specials-free-download\\/"}]', '2018-08-03 04:10:20', '2018-08-03 04:10:28'),
(10, 'Old Man Logan (2015-)', 'http://readcomicsonline.ru/comic/old-man-logan-2015', 'http://readcomicsonline.ru/uploads/manga/old-man-logan-2015/cover/cover_thumb.jpg', '[{"raiting":"4.58"},{"summary":"Fifty years from now, Logan- the man who no longer calls himself Wolverine- will have endured many atrocities: The Marvel Universe''s villains will have banded together and rid the world of its heroes. Logan''s closest friend, Hawkeye, will have been murdered in cold blood right before his eyes. And driven mad by the same radiation that gave him his superhuman strength, Bruce Banner will have fathered a family of hillbilly Hulks...that eventually went on to slaughter Logan''s wife and two children. But now, in the present, Old Man Logan wakes up to discover himself in a world before these atrocities, before the Wasteland. And he''s going to seize this opportunity and change history to ensure that his future never comes to pass."}]', '2018-08-03 04:10:20', '2018-08-03 04:10:28'),
(11, 'Secret Empire (2017-)', 'http://readcomicsonline.ru/comic/secret-empire-2017', 'http://readcomicsonline.ru/uploads/manga/secret-empire-2017/cover/cover_thumb.jpg', '[{"raiting":"3.83"},{"summary":"The Marvel Universe is under siege from within! Captain America, secretly a true believer in the cause of Hydra, has turned his back on the Super Hero community. Using the trust and respect he has gained over the years he has ascended to a position where he can enacts Hydra''s ideals. The death of Jack Flag, the trial of Maria Hill, the second Civil War, the alien Chitauri Queen. All of the dominos of Captain America''s plan have been laid out \\u2013 and it will take only the slightest push to set them into action! Now, the Avengers, the Champions, the Defenders, the Guardians of the Galaxy, the X-Men and more will be tested. As Hydra''s grip tightens around the Marvel Universe, the heroes stand at the precipice of an unprecedented challenge. How will they Marvel Universe cope with this shattering betrayal by the most trusted among them?"}]', '2018-08-03 04:10:20', '2018-08-03 04:10:29'),
(12, 'Avengers (2016-)', 'http://readcomicsonline.ru/comic/avengers-2016', 'http://readcomicsonline.ru/uploads/manga/avengers-2016/cover/cover_thumb.jpg', '[{"raiting":"4.09"},{"summary":"The time has come! Their ranks shattered by Civil War, their spirits weighted down by a toll both personal and spiritual, Earth''s Mightiest Heroes must find the resolve to stand united one final time against their greatest foe! Captain America! Thor! The Vision! The Wasp! Spider-Man! Hercules! When the dust settles, not a one of these valiant heroes will make it to the final page alive! This is KANG WAR ONE!"}]', '2018-08-03 04:10:21', '2018-08-03 04:10:29'),
(13, 'Teen Titans (2016-)', 'http://readcomicsonline.ru/comic/teen-titans-2016', 'http://readcomicsonline.ru/uploads/manga/teen-titans-2016/cover/cover_thumb.jpg', '[{"raiting":"4.21"},{"summary":"The Teen Titans are farther apart than ever before...until Damian Wayne recruits Starfire, Raven, Beast Boy and the new Kid Flash to join him in a fight against his own grandfather, Ra''s al Ghul! But true leadership is more than just calling the shots-is Robin really up to the task? Or will the Teen Titans dismiss this diminutive dictator?"}]', '2018-08-03 04:10:21', '2018-08-03 04:10:30'),
(14, 'Detective Comics (2016-)', 'http://readcomicsonline.ru/comic/detective-comics-2016', 'http://readcomicsonline.ru/uploads/manga/detective-comics-2016/cover/cover_thumb.jpg', '[{"raiting":"4.46"},{"summary":"An unknown predator begins outdoing Batman, taking down dangerous threats with military precision. It''s up to the Dark Knight and series costar Batwoman to rally and train the young heroes of Gotham City to end this mysterious threat!\\r\\n\\r\\nWHAT NOW: Batman and Batwoman begin training Spoiler, Red Robin and Cassandra Cain, but is the villainous Clayface ready for redemption?"}]', '2018-08-03 04:10:21', '2018-08-03 04:10:31'),
(15, 'Action Comics (2016-)', 'http://readcomicsonline.ru/comic/action-comics-2016', 'http://readcomicsonline.ru/uploads/manga/action-comics-2016/cover/cover_thumb.jpg', '[{"raiting":"4.26"},{"summary":"Superman returns to Metropolis just in time to meet the city of tomorrow''s newest protector: Lex Luthor. But it''s not long before these dueling titans meet someone unexpected\\u2014the new Clark Kent!\\r\\n\\r\\nDON''T MISS: ACTION COMICS returns to its original numbering!"}]', '2018-08-03 04:10:21', '2018-08-03 04:10:31'),
(16, 'Titans (2016)', 'http://readcomicsonline.ru/comic/titans-2016', 'http://readcomicsonline.ru/uploads/manga/titans-2016/cover/cover_thumb.jpg', '[{"raiting":"4.79"},{"summary":"Wally West has returned to the DC Universe! And now, the Titans set their sights on a dangerous enemy with the power to change reality itself! But the Titans have never faced a threat this massive before, and with so much on the line, will they be able to stand united as a team? Or will their past mistakes be their undoing?"}]', '2018-08-03 04:10:21', '2018-08-03 04:10:32'),
(17, 'DC Comics Rebirth', 'http://readcomicsonline.ru/comic/dc-comics-rebirth', 'http://readcomicsonline.ru/uploads/manga/dc-comics-rebirth/cover/cover_thumb.jpg', '[{"raiting":"4.55"},{"summary":"A collection of DC''s Rebirth One Shots.\\r\\n\\r\\nDC Rebirth is a 2016 relaunch by DC Comics of its entire line of ongoing monthly superhero comic books. Using the end of The New 52 initiative in May 2016 as its launching point, DC Rebirth is intended to restore the DC Universe to a form much like that prior to the \\"Flashpoint\\" storyline while still incorporating numerous elements of The New 52, including its continuity."}]', '2018-08-03 04:10:21', '2018-08-03 04:10:33'),
(18, 'Nightwing (2016-)', 'http://readcomicsonline.ru/comic/nightwing-2016', 'http://readcomicsonline.ru/uploads/manga/nightwing-2016/cover/cover_thumb.jpg', '[{"raiting":"4.83"},{"summary":"\\"BETTER THAN BATMAN\\" Chapter One\\r\\n\\r\\nBatman taught Nightwing everything he knows\\u2014but what if everything he taught him is wrong? When Dick is stuck with a new mentor who challenges everything Batman taught him, Nightwing has to shatter his concept of justice in order to fight for what he knows is right. Writer Tim Seeley (GRAYSON, BATMAN & ROBIN ETERNAL) launches Nightwing onto a new quest alongside rising talent Javier Fernandez (RED HOOD\\/ARSENAL)."}]', '2018-08-03 04:10:21', '2018-08-03 04:10:33'),
(19, 'Red Hood and the Outlaws (2016-)', 'http://readcomicsonline.ru/comic/red-hood-and-the-outlaws-2016', 'http://readcomicsonline.ru/uploads/manga/red-hood-and-the-outlaws-2016/cover/cover_thumb.jpg', '[{"raiting":"4.87"},{"summary":"\\u201cDark Trinity\\u201d part one! When a turf war puts Black Mask in Red Hood\\u2019s crosshairs, Jason discovers that the False Face Society is not what it seems, and that the organization is about to auction off a powerful weapon. As criminals from all over the globe descend on Gotham City, Jason must prove that he belongs amongst the city\\u2019s worst in order to gain access to this Dark Summit!"}]', '2018-08-03 04:10:21', '2018-08-03 04:10:34'),
(20, 'Civil War II (2016-)', 'http://readcomicsonline.ru/comic/civil-war-ii-2016', 'http://readcomicsonline.ru/uploads/manga/civil-war-ii-2016/cover/cover_thumb.jpg', '[{"raiting":"3.43"},{"summary":"To download the whole Civil War II Collection, please go to this page : DOWNLOAD CIVIL WAR II Complete Collection"}]', '2018-08-03 04:10:21', '2018-08-03 04:10:34'),
(21, 'Steven Universe Ongoing (2017)', 'http://readcomicsonline.ru/comic/steven-universe-ongoing-2017', 'http://readcomicsonline.ru/uploads/manga/steven-universe-ongoing-2017/cover/cover_250x350.jpg', '[{"raiting":"4.47"},{"summary":"We''re bringing Steven Universe back to comic books with more Steven, more gems, and more of the characters we all love in an all-new ongoing series! Writer Melanie Gillman (As the Crow Flies) and artist Katy Farina (The Amazing World of Gumball) are teaming up for the start of a new adventure for the entire gang. Based on Cartoon Network''s Emmy Award-nominated animated series created by Rebecca Sugar about a boy with magical powers who goes on adventures with The Crystal Gems, a team of beings who safeguard the universe. The show is approaching its fourth season and has earned over 32 million fans of all ages worldwide."}]', '2018-08-03 04:10:22', '2018-08-03 04:10:35'),
(22, 'Steven Universe Ongoing (2017)', 'http://readcomicsonline.ru/comic/steven-universe-ongoing-2017', 'http://readcomicsonline.ru/uploads/manga/steven-universe-ongoing-2017/cover/cover_250x350.jpg', '[{"raiting":"4.47"},{"summary":"We''re bringing Steven Universe back to comic books with more Steven, more gems, and more of the characters we all love in an all-new ongoing series! Writer Melanie Gillman (As the Crow Flies) and artist Katy Farina (The Amazing World of Gumball) are teaming up for the start of a new adventure for the entire gang. Based on Cartoon Network''s Emmy Award-nominated animated series created by Rebecca Sugar about a boy with magical powers who goes on adventures with The Crystal Gems, a team of beings who safeguard the universe. The show is approaching its fourth season and has earned over 32 million fans of all ages worldwide."}]', '2018-08-03 04:10:22', '2018-08-03 04:10:35'),
(23, 'Rugrats (2017)', 'http://readcomicsonline.ru/comic/rugrats-2017', 'http://readcomicsonline.ru/uploads/manga/rugrats-2017/cover/cover_250x350.jpg', '[{"raiting":"4"},{"summary":"Hang on to your diapies, babies! We\\u2019re teaming up with Nickelodeon for all-new Rugrats adventures featuring the most intrepid toddlers to ever bust out of a playpen! Tommy, Chuckie, Phil, and Lil have noticed something\\u2014they are being watched. Somehow their parents can see every little thing they can do. They\\u2019re going to have to find a way to have fun while avoiding the electronic eyes of the babycam!"}]', '2018-08-03 04:10:22', '2018-08-03 04:10:36'),
(24, 'Portal Bound Vol. 1 (2018)', 'http://readcomicsonline.ru/comic/portalbound-vol-1-2018', 'http://readcomicsonline.ru/uploads/manga/portalbound-vol-1-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"Their Future Depends on Each Other as Aspen\\u2019s 15-Year Anniversary kicks off with the debut of their newest series! A parallel otherworld exists as a mirror to our own, where science is melded with nature and a warrior spirit defines their true value. A teenage soldier princess, Sybil, is sent off with her Uncle Horuk in an effort to stop her megalomaniac father, Emperor Atilus from destroying two Earths. With a deadly array of monstrous creatures in hot pursuit, Sybil and her uncle race to activate a portal to Earth to find a savior who is also figuring out how to survive\\u2026being a teenager!"}]', '2018-08-03 04:10:22', '2018-08-03 04:10:36'),
(25, 'G.I. Joe: A Real American Hero (2011-)', 'http://readcomicsonline.ru/comic/gi-joe-a-real-american-hero-2011', 'http://readcomicsonline.ru/uploads/manga/gi-joe-a-real-american-hero-2011/cover/cover_250x350.jpg', '[{"raiting":"3"},{"summary":"Picking up from where the ORIGINAL G.I. JOE: A REAL AMERICAN HERO comic book ended, Real American Hero is a core fan''s dream come true! Larry Hama continues his classic G.I. JOE run right here, and RELAUNCHES THE ORIGINAL SERIES!"}]', '2018-08-03 04:10:22', '2018-08-03 04:10:36'),
(26, 'Fathom Vol. 5 (2018-)', 'http://readcomicsonline.ru/comic/fathom-vol-5-2018', 'http://readcomicsonline.ru/uploads/manga/fathom-vol-5-2018/cover/cover_250x350.jpg', '[{"raiting":"1"},{"summary":"1998\\u2019s Best-Selling Title of the Year Celebrates 20 Years in 2018! This all-new adventure for Aspen\\u2019s preeminent hero sees her attempt to navigate an ever-changing world where The Blue are not only present above the surface-but exploited in new and dangerous ways. When a rival nation to The States decides to take control of the global landscape by tapping into the power of The Blue, Aspen Matthews discovers that a new adversary has risen to challenge the notion that she is the most powerful person on the planet-and humanity may suffer the consequences! Michael Turner and Aspen Comics\\u2019 flagship title commemorates its landmark twenty years since its debut in grand fashion!"}]', '2018-08-03 04:10:22', '2018-08-03 04:10:37'),
(27, 'Adventure Time: Beginning of the End (2018-)', 'http://readcomicsonline.ru/comic/adventure-time-beginning-of-the-end-2018', 'http://readcomicsonline.ru/uploads/manga/adventure-time-beginning-of-the-end-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"When Finn breaks a promise he can''t remember making, he is confronted by Chronologius Rex, the lord of Hours and All Time. Finn''s life will be consumed in the infinite first of the fourth dimension unless he and his friends back home can find the moment that explains it all and bring him back him back to Ooo. Finn must confront the ghosts of his past selves, the alternate selves of his present, and all his possible futures, while Jake gather help from all of Ooo and beyond. Together, they must save Finn before he goes beyond the Vanishing point and is erased from every reality."}]', '2018-08-03 04:10:22', '2018-08-03 04:10:37'),
(28, 'WWE Attitude Era 2018 Special', 'http://readcomicsonline.ru/comic/wwe-attitude-era-2018-special', 'http://readcomicsonline.ru/uploads/manga/wwe-attitude-era-2018-special/cover/cover_250x350.jpg', '[{"raiting":"4.5"},{"summary":"ARE YOU READY? The most iconic time in Sports Entertainment history comes to life in untold stories of the WWE. This anthology includes stories looking at Stone Cold Steve Austin, the rivalry between the Brothers of Destruction, Undertaker and Kane, and DX\\u2019s infamous invasion of a certain wrestling program \\u201cdown South\\u201d..."}]', '2018-08-03 04:10:22', '2018-08-03 04:10:38'),
(29, 'Rocko''s Modern Life (2017)', 'http://readcomicsonline.ru/comic/rockos-modern-life-2017', 'http://readcomicsonline.ru/uploads/manga/rockos-modern-life-2017/cover/cover_250x350.jpg', '[{"raiting":"3"},{"summary":"Ryan Ferrier (Regular Show) and Ian McGinty (Adventure Time) continue BOOM! Studios\\u2019 partnership with Nickelodeon with all-new stories about everyone\\u2019s favorite wallaby! When Rocko faces unemployment, a terrible living situation, and increasingly slim job prospects, he is forced to find out just how far he is willing to go to get a job. Includes a bonus short story by KC Green where Ed Bighead finds himself in the dentist chair of Dr. Hutchison!"}]', '2018-08-03 04:10:22', '2018-08-03 04:10:38'),
(30, 'Dark Ark (2017)', 'http://readcomicsonline.ru/comic/dark-ark-2017', 'http://readcomicsonline.ru/uploads/manga/dark-ark-2017/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"The wickedness of mankind has moved the Creator to destroy the world by way of the flood. Noah has been tasked with building an ark to save his family and the animals of the world. But this is not Noah''s story. For darker powers have commanded the sorcerer Shrae to build his own ark and save the unnatural creatures of the world\\u2014such as the vampires, the dragons, the naga, and the manticore. But what will happen on a vessel crawling with monsters, where insidious intrigue and horrific violence are the rule of law?"}]', '2018-08-03 04:10:23', '2018-08-03 04:10:39'),
(31, 'Bubba Ho-Tep and the Cosmic Blood-Suckers (2018-)', 'http://readcomicsonline.ru/comic/bubba-hotep-and-the-cosmic-bloodsuckers-2018', 'http://readcomicsonline.ru/uploads/manga/bubba-hotep-and-the-cosmic-bloodsuckers-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"From the mind of creator Joe R. Lansdale comes a prequel to the cult-classic film! President Nixon has discovered an alien threat, and he knows there''s only one man he can reach out to for help: Elvis Presley. But will Elvis be enough to defeat a horde of Cosmic Blood-Suckers?"}]', '2018-08-03 04:10:23', '2018-08-03 04:10:39'),
(32, 'Skyward (2018-)', 'http://readcomicsonline.ru/comic/skyward-2018', 'http://readcomicsonline.ru/uploads/manga/skyward-2018/cover/cover_250x350.jpg', '[{"raiting":"2.5"},{"summary":"\\"MY LOW-G LIFE,\\" Part One One day, gravity on earth suddenly became a fraction of what it is now. Twenty years later, humanity has adapted to its new low-gravity reality. And to Willa Fowler, a woman born just after G-day, it\\u2019s\\u2026well, it\\u2019s pretty awesome, actually. You can fly through the air! I mean, sure, you can also die if you jump too high. So you just don\\u2019t jump too high. And maybe don\\u2019t stumble into a dangerous plan to bring gravity back that could get you killed\\u2026. From writer JOE HENDERSON (showrunner of Fox\\u2019s Lucifer) and artist LEE GARBETT (Lucifer, Loki: Agent of Asgard), SKYWARD is an adventure-filled exploration of our world turned upside down and a young woman\\u2019s journey to find her place in it."}]', '2018-08-03 04:10:23', '2018-08-03 04:10:40'),
(33, 'Teenage Mutant Ninja Turtles Universe (2016)', 'http://readcomicsonline.ru/comic/teenage-mutant-ninja-turtles-universe-2016', 'http://readcomicsonline.ru/uploads/manga/teenage-mutant-ninja-turtles-universe-2016/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"Introducing a new era in TMNT! This series will explore characters and story-lines that are pivotal to the IDW TMNT universe! When a mysterious new mutant targets Baxter Stockman, it will be up to the TMNT to reluctantly save him. Little does everyone know that a larger trap is being laid by a new arch-foe! Plus a back-up story from TMNT co-creator Kevin Eastman and comics legend Bill Sienkiewicz!"}]', '2018-08-03 04:10:23', '2018-08-03 04:10:40'),
(34, 'Teenage Mutant Ninja Turtles: Bebop & Rocksteady Hit the Road! (2018-)', 'http://readcomicsonline.ru/comic/teenage-mutant-ninja-turtles-bebop-rocksteady-hit-the-road-2018', 'http://readcomicsonline.ru/uploads/manga/teenage-mutant-ninja-turtles-bebop-rocksteady-hit-the-road-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"Everyone\\u2019s favorite mutated masters of mayhem, Bebop and Rocksteady, are road tripping back to NYC! But before they can get started on their journey across America, they run into a crazy old enemy who\\u2019s bent on derailing their trip before it can begin!"}]', '2018-08-03 04:10:23', '2018-08-03 04:10:40'),
(35, 'Star Wars (2015-)', 'http://readcomicsonline.ru/comic/star-wars-2015', 'http://readcomicsonline.ru/uploads/manga/star-wars-2015/cover/cover_250x350.jpg', '[{"raiting":"4.5"},{"summary":"THE GREATEST SPACE ADVENTURE OF ALL TIME RETURNS TO MARVEL! Luke Skywalker and the ragtag band of rebels fighting against the Galactic Empire are fresh off their biggest victory yet\\u2014the destruction of the massive battle station known as the Death Star. But the Empire\\u2019s not toppled yet! Join Luke along with Princess Leia, smugglers Han Solo and Chewbacca, droids C-3PO and R2-D2 and the rest of the Rebel Alliance as they strike out for freedom against the evil forces of Darth Vader and his master, the Emperor. Written by Jason Aaron (Original Sin, Thor: God of Thunder) and with art by John Cassaday (Astonishing X-Men, Uncanny Avengers), this is the Star Wars saga as only Marvel Comics could make it!"}]', '2018-08-03 04:10:23', '2018-08-03 04:10:41'),
(36, 'The Curse of Brimstone (2018-)', 'http://readcomicsonline.ru/comic/the-curse-of-brimstone-2018', 'http://readcomicsonline.ru/uploads/manga/the-curse-of-brimstone-2018/cover/cover_250x350.jpg', '[{"raiting":"3.5"},{"summary":"Joe Chamberlain would do anything to save his small, forgotten town\\u2014even make a deal with the devil. But things get worse, and Joe finds himself cursed with the power of BRIMSTONE. With the power of fire and destruction coursing through his hands, Joe must now track down and destroy the demon he made his deal with before the power he now wields destroys the town he was trying to save. But as the fiery pain inside him grows, can this young man overcome his own demons before his power rips him apart from the inside out?"}]', '2018-08-03 04:10:23', '2018-08-03 04:10:42'),
(37, 'Survival Fetish (2018-)', 'http://readcomicsonline.ru/comic/survival-fetish-2018', 'http://readcomicsonline.ru/uploads/manga/survival-fetish-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"Downtown Honolulu is a sniper alley, and Saheer runs it better than anyone. He''s a local celebrity for transporting medicine and information across a no-man''s land occupied by militias and street gangs. But what people say about you is never the full story, and when the cheers die out Saheer is left with just his anxieties... and his secrets. The first of a five-issue series that keeps its foot pressed on your adrenal gland. From Patrick Kindlon (We Can Never Go Home, There''s Nothing There, S.H.I.E.L.D.: Quake) and illustrator Antonio Fuso (James Bond), Survival Fetish is a pulse-pounding thrill-ride that mixes political intrigue with deep characters and high octane action."}]', '2018-08-03 04:10:23', '2018-08-03 04:10:42'),
(38, 'X-Men Gold (2017)', 'http://readcomicsonline.ru/comic/xmen-gold-2017', 'http://readcomicsonline.ru/uploads/manga/xmen-gold-2017/cover/cover_250x350.jpg', '[{"raiting":"3.5"},{"summary":"It''s the 50th Anniversary of the X-Men, ring it in with some of the greatest creators to ever work on the X-Men!"}]', '2018-08-03 04:10:23', '2018-08-03 04:10:42'),
(39, 'X-Men Gold (2017)', 'http://readcomicsonline.ru/comic/xmen-gold-2017', 'http://readcomicsonline.ru/uploads/manga/xmen-gold-2017/cover/cover_250x350.jpg', '[{"raiting":"3.5"},{"summary":"It''s the 50th Anniversary of the X-Men, ring it in with some of the greatest creators to ever work on the X-Men!"}]', '2018-08-03 04:10:23', '2018-08-03 04:10:43'),
(40, 'Xerxes: The Fall of the House of Darius and the Rise of Alexander (2018-)', 'http://readcomicsonline.ru/comic/xerxes-the-fall-of-the-house-of-darius-and-the-rise-of-alexander-2018', 'http://readcomicsonline.ru/uploads/manga/xerxes-the-fall-of-the-house-of-darius-and-the-rise-of-alexander-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"Xerxes: The God King!\\r\\n\\r\\nFrank Miller returns to the world of 300 with this sprawling historical epic! Persian King Xerxes sets out to conquer the world to avenge his father Darius''s defeat and create an empire, unlike anything the world has ever seen . . . Until the hardy Greeks produce a god king of their own, Alexander the Great."}]', '2018-08-03 04:10:24', '2018-08-03 04:10:43'),
(41, 'Weapon X (2017-)', 'http://readcomicsonline.ru/comic/weapon-x-2017', 'http://readcomicsonline.ru/uploads/manga/weapon-x-2017/cover/cover_250x350.jpg', '[{"raiting":"3.88"},{"summary":"Decades ago, the Weapon X program produced the deadliest mutant killers on the planet. Now, with more research, more funding and more Adamantium at its disposal, the Weapon X program is creating new killers for old targets: Old Man Logan. Sabretooth. Lady Deathstrike. Weapon X isn''t just experimenting on mutants anymore\\u2026it''s eradicating them. All of them. Plus: Deadlier and more shadowy than ever, you won''t believe who''s taken the job as Director of Weapon X! Reuniting X-Men: Phoenix \\u2014 Endsong creative team GREG PAK (World War Hulk) and GREG LAND (Uncanny X-Men)!"}]', '2018-08-03 04:10:24', '2018-08-03 04:10:44'),
(42, 'We Are The Danger (2018-)', 'http://readcomicsonline.ru/comic/we-are-the-danger-2018', 'http://readcomicsonline.ru/uploads/manga/we-are-the-danger-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"Starting as the new girl in your senior year of high school is never easy, and Julie Malliari is having a terrible first day -- until she meets Tabitha. After a night out at a rock show, their friendship quickly grows and, before they know it, the two form a band with their sights set on a record deal... they just need to win it in a nationwide Battle of the Bands competition. With Tabitha''s rival keen to take the prize for herself, it''s a battle not to be missed... From artist and writer Fabian Lelay (Jade Street Protection Services), colorist Claudia Aguirre (Kim & Kim), and letterer Taylor Esposito comes this exuberant tale of friendship, growing up, and rock ''n roll."}]', '2018-08-03 04:10:24', '2018-08-03 04:10:44'),
(43, 'The Wilds (2018)', 'http://readcomicsonline.ru/comic/the-wilds-2018', 'http://readcomicsonline.ru/uploads/manga/the-wilds-2018/cover/cover_250x350.jpg', '[{"raiting":"3"},{"summary":"After a cataclysmic plague sweeps across America, survivors come together to form citystate-like communities for safety."}]', '2018-08-03 04:10:24', '2018-08-03 04:10:45'),
(44, 'The Walking Dead (2003-)', 'http://readcomicsonline.ru/comic/the-walking-dead-2003', 'http://readcomicsonline.ru/uploads/manga/the-walking-dead-2003/cover/cover_250x350.jpg', '[{"raiting":"4.73"},{"summary":"An epidemic of apocalyptic proportions has swept the globe, causing the dead to rise and feed on the living. In a matter of months, society has crumbled; there is no government, no grocery stores, no mail delivery, no cable TV.\\r\\n\\r\\nRick Grimes finds himself one of the few survivors in this terrifying world. He was a small town cop who had only fired his weapon a couple times but never at anyone and had only ever seen one dead body. Separated from his family, he must sort through the death and horror to try and find his wife and son. In a world ruled by the dead, people are forced to finally begin living. Issue #1 - 159 can be downloaded at : http:\\/\\/getcomics.info\\/other-comics\\/the-walking-dead-comics-1-138-specials-free-download\\/"}]', '2018-08-03 04:10:24', '2018-08-03 04:10:45'),
(45, 'The Seeds (2018-)', 'http://readcomicsonline.ru/comic/the-seeds-2018', 'http://readcomicsonline.ru/uploads/manga/the-seeds-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"In a world much like our own, people are smashing their phones and moving to the lawless tech-free Zone B.  A few cantankerous aliens have come to collect the last dregs of humanity''s essence for the celestial embryo bank. One of them falls in love. Astra is an idealistic journalist who stumbles into the story of a lifetime, only to realize that if she reports it, she''ll destroy the last hope of a dying world. How far will she go to get her story?"}]', '2018-08-03 04:10:24', '2018-08-03 04:10:46'),
(46, 'The Mainstream (2018-)', 'http://readcomicsonline.ru/comic/the-mainstream-2018', 'http://readcomicsonline.ru/uploads/manga/the-mainstream-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"There are people on THIS Earth that do not belong. It\\u2019s up to a Chicago detective and a covert, inter-dimensional police force to send them back where they came from! Don\\u2019t miss this brand new five issue mini-series from the creative minds of Michael Dolce (Descendant, The Sire), Talent Caldwell (Superman, Fathom and WildCATS), Tony Moy (X-Files), and Darren Sanchez (Foxwood Falcons, Celestial Alliance)."}]', '2018-08-03 04:10:24', '2018-08-03 04:10:46'),
(47, 'The Last Siege (2018-)', 'http://readcomicsonline.ru/comic/the-last-siege-2018', 'http://readcomicsonline.ru/uploads/manga/the-last-siege-2018/cover/cover_250x350.jpg', '[{"raiting":"4"},{"summary":"A tale of blood, desperation, and loss. New York Times bestselling author LANDRY Q. WALKER joins artist JUSTIN GREENWOOD for an all-new ONGOING SERIES\\u2014THE LAST SIEGE! Spaghetti Western storytelling meets Game of Thrones atmosphere in this gritty medieval war story, as a mysterious stranger arrives at a castle overrun with brutal soldiers bent on usurping the throne of the rightful heir\\u2014an 11-year-old girl. An action-packed, genre-twisting epic, THE LAST SIEGE begins!"}]', '2018-08-03 04:10:24', '2018-08-03 04:10:46'),
(48, 'The Highest House (2018)', 'http://readcomicsonline.ru/comic/the-highest-house-2018', 'http://readcomicsonline.ru/uploads/manga/the-highest-house-2018/cover/cover_250x350.jpg', '[{"raiting":"4.5"},{"summary":"The creators behind The Unwritten, Mike Carey and Peter Gross, invite you into The Highest House, the story of a slave boy named Moth, who makes friends with a powerful entity called Obsidian that promises advancement and happiness. Clearly, Obsidian has a hidden agenda, but Moth has ambitions and plans of his own..."}]', '2018-08-03 04:10:24', '2018-08-03 04:10:47'),
(49, 'Stray Bullets: Sunshine & Roses (2015-)', 'http://readcomicsonline.ru/comic/stray-bullets-sunshine-roses-2015', 'http://readcomicsonline.ru/uploads/manga/stray-bullets-sunshine-roses-2015/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"STRAY BULLETS CONTINUES WITH THE BEGINNING OF A BRAND-NEW ARC OF STORIES! SUNSHINE AND ROSES is about violence, love, and really bad decisions. The Baltimore underworld is falling apart at the seams and blood has been spilt. Where and when things went to hell in a handbasket can be traced back to a time a few years earlier, when a man named Harry ran the city, Spanish Scott and Monster enforced the rules, and an insecure young man named Orson met a wild and crazy girl named Beth. The two together cooked up the boldest, most outlandish, and just about the stupidest plan ever devised-a plan to steal a whole lot of Harry''s money and drugs and get a little revenge along the way. While every issue of STRAY BULLETS presents a complete story, the start of each new arc is the perfect place to jump on board and see what everybody else is talking about."}]', '2018-08-03 04:10:25', '2018-08-03 04:10:47'),
(50, 'Star Wars: The Last Jedi Adaptation (2018)', 'http://readcomicsonline.ru/comic/star-wars-the-last-jedi-adaptation-2018', 'http://readcomicsonline.ru/uploads/manga/star-wars-the-last-jedi-adaptation-2018/cover/cover_250x350.jpg', '[{"raiting":"2.5"},{"summary":"The Resistance has found Luke Skywalker! But the First Order is hot on their tail\\u2026and they are out for blood. Join writer Gary Whitta (ROGUE ONE: A STAR WARS STORY) and artist Michael Walsh (STAR WARS ANNUAL, HAWKEYE and THE VISION) as they take on the adventures of Force prodigy Rey, ace pilot Poe Dameron, and ex-First Order recruit Finn from the hit blockbuster STAR WARS: THE LAST JEDI \\u2013 featuring never-before-seen scenes of your favorite characters!"}]', '2018-08-03 04:10:25', '2018-08-03 04:10:48'),
(51, 'Spidey: School''s Out (2018)', 'http://readcomicsonline.ru/comic/spidey-schools-out-2018', 'http://readcomicsonline.ru/uploads/manga/spidey-schools-out-2018/cover/cover_250x350.jpg', '[{"raiting":"3.8"},{"summary":"Peter Parker just survived his first year as the Amazing Spider-Man AND a year of high school! What is he going to do next? He''s going to Stark science camp! A week indoors with the coolest technology in the world is a dream come true for Peter--and a bonanza for one Spider-foe who''s seriously upgraded his arsenal. Can Spider-Man keep the camp safe, and keep his identity secret from his first dorm mate, while Peter Parker makes new friends and finishes his project on time?"}]', '2018-08-03 04:10:25', '2018-08-03 04:10:48'),
(52, 'Shade, The Changing Woman (2018-)', 'http://readcomicsonline.ru/comic/shade-the-changing-woman-2018', 'http://readcomicsonline.ru/uploads/manga/shade-the-changing-woman-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"Shade has shed her alien identity. She\\u2019s stepped out of her original Earth body and into another one. Now, free of the burdens of any past life, and finally on her own, she sets out to see more of her new home. But how does she cope when the madness takes all the human emotions she was forced to confront in the Milk Wars and turns them into a bouillabaisse of memory and confusion? And to make it even more challenging, Shade must also face her namesake, the original Changing Man."}]', '2018-08-03 04:10:25', '2018-08-03 04:10:49'),
(53, 'Robots Vs. Princesses (2018-)', 'http://readcomicsonline.ru/comic/robots-vs-princesses-2018', 'http://readcomicsonline.ru/uploads/manga/robots-vs-princesses-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"The comic event of the year has arrived! When plucky Princess Zara stumbles upon the Decimator defector Wheeler, she sets in motion events that will pit the spritely cleverness of fairy tale princesses against the raw power of giant robots! The dream match you never thought you\\u2019d see begins here. Don\\u2019t miss it!"}]', '2018-08-03 04:10:25', '2018-08-03 04:10:49'),
(54, 'Red Sonja (2016-)', 'http://readcomicsonline.ru/comic/red-sonja-2016', 'http://readcomicsonline.ru/uploads/manga/red-sonja-2016/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"Through the plains of Hyrkania, a message sweeps through the scattered peoples of the nation. Bells ring, horns blow, voices shout - the King is dying! Red Sonja rides to save the King from his doom as the powers of Hyboria crowd around to strike when the kingdom is weakest. But a dread new power rises from within Hyrkania''s own borders, bent on defending its homeland - no matter the cost, no matter what its people become. A defining chapter of the Red Sonja saga - dark, clever, vicious, and funny - as the She-Devil with a Sword must stop the rise of a brutal new regime... her own people!"}]', '2018-08-03 04:10:25', '2018-08-03 04:10:50'),
(55, 'Quantum Age (2018-)', 'http://readcomicsonline.ru/comic/quantum-age-2018', 'http://readcomicsonline.ru/uploads/manga/quantum-age-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"Set in the world of the Eisner Award-winning Black Hammer series--but a thousand years in the future--a collection of superheroes, inspired by the legendary heroes of Black Hammer Farm, must band together to save the planet from an authoritarian regime. A young Martian must find a way to reform The Quantum League to save the world while solving the riddle of what happened to the great heroes of the twentieth century."}]', '2018-08-03 04:10:25', '2018-08-03 04:10:50'),
(56, 'Project: Superpowers Vol. 2 (2018-)', 'http://readcomicsonline.ru/comic/project-superpowers-vol-2-2018', 'http://readcomicsonline.ru/uploads/manga/project-superpowers-vol-2-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"Superpowers #0: Project Superpowers is Back! Written by Rob (Suicide Squad) Williams, illustrated by Sergio (Swords of Sorrow, Superman) Davila, and featuring an all-star roster of cover artists, this introductory priced issue is the perfect starting point for the most ambitious superhero story of 2018. An all-new threat faces the Earth, while the team faces turmoil from within and must overcome all obstacles to prove their worth and value in a world that desperately needs its heroes. The Death Defying Devil, Samson, Black Terror, Masquerade, Green Lama, Scarab and more are all here as the adventure begins again.. Featuring an introductory story leading right into the all-new #1 next month, Project Superpowers #0 is action-packed and introductory priced. Includes bonus materials and 16 pages of original story."}]', '2018-08-03 04:10:26', '2018-08-03 04:10:51'),
(57, 'Paradiso (2017)', 'http://readcomicsonline.ru/comic/paradiso-2017', 'http://readcomicsonline.ru/uploads/manga/paradiso-2017/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"The Midnight Event forever changed the world. Now, centuries later, Jack Kryznan arrives on the outskirts of Paradiso City, haunted by fragments of childhood memories and in possession of a mysterious device\\u2014one with the power to change the destiny of this living breathing metropolis, the people who dwell within, and the guardians who strive for and against it."}]', '2018-08-03 04:10:26', '2018-08-03 04:10:51'),
(58, 'Paradise Court (2018-)', 'http://readcomicsonline.ru/comic/paradise-court-2018', 'http://readcomicsonline.ru/uploads/manga/paradise-court-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"While taking a cross country trip, a young couple stops to visit one of their long lost friends who live in an idyllic gated community in the Midwest. Not long after they arrive, they find out that a girl has gone missing and that something sinister may be lurking behind the mansions and well-manicured lawns of Paradise Court."}]', '2018-08-03 04:10:26', '2018-08-03 04:10:52'),
(59, 'Noble (2017)', 'http://readcomicsonline.ru/comic/noble-2017', 'http://readcomicsonline.ru/uploads/manga/noble-2017/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"Catalyst Prime has begun! One year after \\"The Event,\\" missing astronaut David Powell has resurfaced! With dangerous new abilities and no memory of the man he once was. While desperately trying to regain his identity David quickly finds himself a man on the run from shadowy forces as well as his forgotten past. From writer Brandon Thomas (Horizon, Civil War II: Choosing Sides), artist Roger Robinson (Batman: Gotham Knights, Solo Avengers), and colorist Juan Fernandez."}]', '2018-08-03 04:10:26', '2018-08-03 04:10:53'),
(60, 'Marvel Rising: Ms. Marvel/Squirrel Girl (2018)', 'http://readcomicsonline.ru/comic/marvel-rising-ms-marvelsquirrel-girl-2018', 'http://readcomicsonline.ru/uploads/manga/marvel-rising-ms-marvelsquirrel-girl-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"THE GAME IS UP IN THE PENULTIMATE CHAPTER OF MARVEL RISING! When Ember Quade traps Ms. Marvel, Squirrel Girl and their friends in a video-game reality, they\\u2019ll have to fight their way through the terrifying villain hordes of Ember\\u2019s imagination! But when they reach the final level, even Ember will be surprised at what they find. All the cards hit the table as award-winning writers Devin Grayson, G. Willow Wilson and Ryan North take MARVEL RISING to its heights!"}]', '2018-08-03 04:10:26', '2018-08-03 04:10:53'),
(61, 'Last Song (2017)', 'http://readcomicsonline.ru/comic/last-song-2017', 'http://readcomicsonline.ru/uploads/manga/last-song-2017/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"Nicky Marshall was saved by rock and roll -- or so he likes to think. An awkward upbringing and turmoil following his father''s suicide led Nicky to form a band called Ecstasy with his childhood friend Drey. The music takes them to Los Angeles, raw and gritty and teeming with personalities. Nicky thinks they''re ready for stardom, but no one''s ever ready for stardom. This first of four oversized issues begins in the 1980s, grows out of grassroots clubs & introduces Ecstasy to the world -- whether it''s ready for them or not. From the brand new team of Holly Interlandi on scripts and Sally Cantirino on pencils & inks, this unique, heartbreaking story is about letting the music in... how it changes you and affects everyone around you, for better & worse."}]', '2018-08-03 04:10:26', '2018-08-03 04:10:54'),
(62, 'Image Plus Vol. 2 (2017)', 'http://readcomicsonline.ru/comic/image-plus-vol-2-2017', 'http://readcomicsonline.ru/uploads/manga/image-plus-vol-2-2017/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"Volume two of the Diamond Gem Award-winning comics magazine IMAGE+ begins now! Fans have been eagerly awaiting the return of SCOTT SNYDER & JOCK''s smash-hit horror series WYTCHES ever since the first season ended on a brutal cliffhanger. Now, they''re back with a taste for the upcoming second season of the series by serializing what happens next in IMAGE+! How did Sailor make it to safety? What has she been doing since? The answers can be found exclusively in IMAGE+ with an extra-sized first chapter this issue. In addition to the return of WYTCHES, IMAGE+ is now a hefty 80 PAGES at no additional cost, meaning more room for longer, more fascinating interviews, exciting previews, and in-depth features on comics, creators, cosplay, conventions, and comics culture. IMAGE+ remains your number one source for news and information about Image Comics, and now''s the perfect time to get in on the ground floor."}]', '2018-08-03 04:10:26', '2018-08-03 04:10:54'),
(63, 'Hunt For Wolverine: Weapon Lost (2018)', 'http://readcomicsonline.ru/comic/hunt-for-wolverine-weapon-lost-2018', 'http://readcomicsonline.ru/uploads/manga/hunt-for-wolverine-weapon-lost-2018/cover/cover_250x350.jpg', '[{"raiting":"3.5"},{"summary":"WOLVERINE MAY BE THE BEST THERE IS AT WHAT HE DOES... BUT SO ARE THEY! As one of the biggest mysteries in the MARVEL UNIVERSE unfolds, DAREDEVIL assembles a squad of uncanny detectives to track down WOLVERINE - MISTY KNIGHT, FRANK MCGEE and the mutant known as CYPHER. Investigating recent sightings across the globe of a man believed to be LOGAN, the squad uncovers a deep conspiracy with huge ramifications for the RETURN OF WOLVERINE."}]', '2018-08-03 04:10:26', '2018-08-03 04:10:55'),
(64, 'Harley Quinn (2016-)', 'http://readcomicsonline.ru/comic/harley-quinn-2016', 'http://readcomicsonline.ru/uploads/manga/harley-quinn-2016/cover/cover_250x350.jpg', '[{"raiting":"3"},{"summary":"\\u201cDie Laughing\\u201d part one! Welcome back to Harley Quinn\\u2019s crazy world on Coney Island\\u2026now get ready to wave goodbye, because everyone there just might get eaten alive! Harley\\u2019s gotta protect her neighborhood against an all-out zombie apocalypse! Break out the chainsaws, everybody!"}]', '2018-08-03 04:10:27', '2018-08-03 04:10:55'),
(65, 'Green Arrow (2016-)', 'http://readcomicsonline.ru/comic/green-arrow-2016', 'http://readcomicsonline.ru/uploads/manga/green-arrow-2016/cover/cover_250x350.jpg', '[{"raiting":"4.67"},{"summary":"As Oliver struggles with how he can fight \\"the man\\" when his huge fortune makes him the man, he and Black Canary uncover a deadly new threat to Seattle that cuts the Archer to the bone.\\r\\n\\r\\nTHEY SAID IT: \\"My touchstones are [former GA writers] Dennis O''Neil and Mike Grell, while trying to make the series my own,\\" says writer Benjamin Percy. \\"Green Arrow will be a politically and culturally relevant series. Expect stories that aim a broadhead into the zeitgeist, that are ripped from the headlines.\\""}]', '2018-08-03 04:10:27', '2018-08-03 04:10:56'),
(66, 'Giant Days (2015-)', 'http://readcomicsonline.ru/comic/giant-days-2015', 'http://readcomicsonline.ru/uploads/manga/giant-days-2015/cover/cover_250x350.jpg', '[{"raiting":"4.75"},{"summary":"Susan, Esther, and Daisy started at university three weeks ago and became fast friends because their dorm rooms were next to each other. Now, away from home for the first time, all three want to reinvent themselves. But in the face of hand-wringing boys, \\u201cpersonal experimentation,\\u201d influenza, mystery-mold, nu-chauvinism, and the willful, unwanted intrusion of \\u201cacademia,\\u201d they may be lucky just to make it to spring alive."}]', '2018-08-03 04:10:27', '2018-08-03 04:10:56');
INSERT INTO `scrapdatas` (`id`, `name`, `related_url`, `img_url`, `related_details`, `created_at`, `updated_at`) VALUES
(67, 'Ghostbusters: Crossing Over (2018-)', 'http://readcomicsonline.ru/comic/ghostbusters-crossing-over-2018', 'http://readcomicsonline.ru/uploads/manga/ghostbusters-crossing-over-2018/cover/cover_250x350.jpg', '[{"raiting":"3"},{"summary":"For a while now, the original Ghostbusters have had access to an interdimensional portal that has given them all-new ways to research the paranormal and consult with Ghostbusters throughout the multiverse\\u2026 but they haven''t shared this tech with any of those other Ghostbusters, and some don''t think that''s fair. That''s why, after a chance meeting, Jillian Holtzmann and Ron Alexander have decided to right this wrong and cobble together their own working portal... which unintentionally unleashes the contents of the Ghostbusters'' Containment Unit! That''s a lot of ghosts, and it''s going to take a lot of Ghostbusters to recapture them. In fact, it''s going to take ALL of them. Crossing Over starts here!"}]', '2018-08-03 04:10:27', '2018-08-03 04:10:56'),
(68, 'Frozen: Breaking Boundaries (2018-)', 'http://readcomicsonline.ru/comic/frozen-breaking-boundaries-2018', 'http://readcomicsonline.ru/uploads/manga/frozen-breaking-boundaries-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"Elsa and Anna are ready to get to the bottom of things when the peace of their beloved kingdom is disrupted: a wild animal is loose in the village, there is destruction in the forest, and tension is brewing in a nearby kingdom. Luckily this queen and princess will have the help of Olaf, Kristoff . . . and a mysterious, adventurous young woman!"}]', '2018-08-03 04:10:27', '2018-08-03 04:10:57'),
(69, 'Eclipse (2016-)', 'http://readcomicsonline.ru/comic/eclipse-2016', 'http://readcomicsonline.ru/uploads/manga/eclipse-2016/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"Imagine if sunlight burned you alive. In the near future, a mysterious solar event has transformed the sun''s light into deadly immolating rays. The world''s few survivors now live in nocturnal cities. But a killer emerges who uses sunlight to burn his victims, and when he targets the daughter of a solar power mogul, it falls to a disillusioned solar engineer to protect her."}]', '2018-08-03 04:10:27', '2018-08-03 04:10:57'),
(70, 'Deathstroke (2016-)', 'http://readcomicsonline.ru/comic/deathstroke-2016', 'http://readcomicsonline.ru/uploads/manga/deathstroke-2016/cover/cover_250x350.jpg', '[{"raiting":"4.64"},{"summary":"\\u201cThe Professional\\u201d part one! Deathstroke\\u2019s latest contract takes him to a war-torn African country, where he finds himself caught in the middle of a disintegrating alliance between a ruthless dictator and a deadly super-villain. With an entire nation at stake, Slade Wilson must choose between fulfilling his contract and saving an old friend."}]', '2018-08-03 04:10:27', '2018-08-03 04:10:58'),
(71, 'Deadpool (2018-)', 'http://readcomicsonline.ru/comic/deadpool-2018', 'http://readcomicsonline.ru/uploads/manga/deadpool-2018/cover/cover_250x350.jpg', '[{"raiting":"3.67"},{"summary":"MERCIN\\u2019 FOR A LIVING! Skottie Young and Nic Klein bring you the craziest tales of the Regeneratin\\u2019 Degenerate yet! It\\u2019s been a while since Deadpool\\u2019s had to merc to make ends meet, but things are tough all over. While Deadpool tries to get his humble mercenary-for-hire business back off the ground, a catastrophic threat so unfathomably huge, so mind-breakingly cataclysmic it defies description, is heading toward Earth, and there\\u2019s only ONE PERSON WHO CAN STOP IT!!! Oh no, wait\\u2026it\\u2019s not Wade, is it? Oh, %[email\\u00a0protected]#. It\\u2019s Wade."}]', '2018-08-03 04:10:28', '2018-08-03 04:10:58'),
(72, 'Cloak and Dagger (2018-)', 'http://readcomicsonline.ru/comic/cloak-and-dagger-2018', 'http://readcomicsonline.ru/uploads/manga/cloak-and-dagger-2018/cover/cover_250x350.jpg', '[{"raiting":"3.67"},{"summary":"For years, Tyrone Johnson and Tandy Bowen were the super hero duo called CLOAK AND DAGGER -- waging a citywide war on drugs, organized crime and corporate greed. In recent years, their crusade has taken them across the globe, fighting alongside Spider-Man, The X-Men and even The Avengers, and though they''ve drifted apart, a dangerous threat from their past has resurfaced -- one that will force Cloak and Dagger to reunite and come to terms with their truest feelings for one another and the past they share!"}]', '2018-08-03 04:10:28', '2018-08-03 04:10:59'),
(73, 'Cellies (2018-)', 'http://readcomicsonline.ru/comic/cellies-2018', 'http://readcomicsonline.ru/uploads/manga/cellies-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"It''s Halloween season, when Seven Sails theme park''s Shocktober Nights rule! Budding teen rebel Rey decides to ditch work to join her friends for spooky fun, and asks Devin to cover for her. One thing though: Rey''s parents are a little (read: very) strict! Devin must wait for Rey to rush to Jog Mobile by 9pm \\u2013 after closing \\u2013 in time for her parents to pick her up. But Parker and her friends have other plans. Will Rey make it back in time? Can Devin keep her out of trouble?"}]', '2018-08-03 04:10:28', '2018-08-03 04:10:59'),
(74, 'Captain America (2018-)', 'http://readcomicsonline.ru/comic/captain-america-2018', 'http://readcomicsonline.ru/uploads/manga/captain-america-2018/cover/cover_250x350.jpg', '[{"raiting":"4.2"},{"summary":"IT IS WINTER IN AMERICA.For over 70 years, he has stood in stalwart defense of our country and its people. But in the aftermath of Hydra\\u2019s takeover of the nation, Captain America is a figure of controversy, carrying a tarnished shield\\u2026and a new enemy is rising! Who are the Power Elite? And how do they intend to co-opt and corrupt the symbol that is Captain America?"}]', '2018-08-03 04:10:28', '2018-08-03 04:11:00'),
(75, 'Breathless (2018-)', 'http://readcomicsonline.ru/comic/breathless-2018', 'http://readcomicsonline.ru/uploads/manga/breathless-2018/cover/cover_250x350.jpg', '[{"raiting":"3"},{"summary":"It''s Buffy the Vampire Slayer if the villains were big pharma. Scout Turner works as a cryptozoologist, examining and cataloguing supernatural creatures for scientific purposes. When she discovers the cure for asthma in the venom of a new breed of monster, she quickly finds herself on the run from Kenilworth Pharmaceuticals and the monsters that they''ve hired to kill her. With no one by her side but her clueless assistant, a morally ambiguous succubus, and her geriatric dog, Scout goes on the run... but in a world controlled by money and drugs, can she escape the reaching claws of a medical monopoly? From Pat Shand (Destiny NY, Guardians of the Galaxy) and Renzo Rodriguez (Hellchild) comes this healthcare horror story about the monsters creeping in the dark... human or otherwise."}]', '2018-08-03 04:10:28', '2018-08-03 04:11:00'),
(76, 'Bloodstrike (2018-)', 'http://readcomicsonline.ru/comic/bloodstrike-2018', 'http://readcomicsonline.ru/uploads/manga/bloodstrike-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"\\"BRUTALISTS,\\" Part One In the spirit of Bloodstrike''s groundbreaking carnage, the creator behind the indie hit Copra shines a light on Image''s most extreme series. Witness the origin of Cabbot as he launches his undead strikeforce upon the world!"}]', '2018-08-03 04:10:28', '2018-08-03 04:11:01'),
(77, 'Ben Reilly: Scarlet Spider (2017-)', 'http://readcomicsonline.ru/comic/ben-reilly-scarlet-spider-2017', 'http://readcomicsonline.ru/uploads/manga/ben-reilly-scarlet-spider-2017/cover/cover_250x350.jpg', '[{"raiting":"4.64"},{"summary":"One of the most controversial characters in comics has returned \\u2014 and the controversy has only BEGUN! In the aftermath of THE CLONE CONSPIRACY, Ben has a new take on life\\u2026and he''s not the same Scarlet Spider he was before. Come witness what will be the most talked about comic of the year!"}]', '2018-08-03 04:10:28', '2018-08-03 04:11:01'),
(78, 'Astonishing X-Men (2017-)', 'http://readcomicsonline.ru/comic/astonishing-xmen-2017', 'http://readcomicsonline.ru/uploads/manga/astonishing-xmen-2017/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"ONLY THE X-MEN CAN SAVE US! An ancient evil is attacking the world''s most powerful minds. It will have them by the time you finish this sentence, and a moment later, it will have us all. A band of X-MEN discovers the truth behind the threat, but there is no time left. PSYLOCKE, OLD MAN LOGAN, BISHOP, ARCHANGEL, FANTOMEX, ROGUE and GAMBIT will attempt to save a world that hates and fears them. Why? BECAUSE THEY ARE THE X-MEN. From blockbuster writer CHARLES SOULE and joined by a roster of superstar artists beginning with JIM CHEUNG. ASTONISHING X-MEN. It''s the X-book you need."}]', '2018-08-03 04:10:28', '2018-08-03 04:11:02'),
(79, 'Infinity Wars (2018)', 'http://readcomicsonline.ru/comic/infinity-wars-2018', 'http://readcomicsonline.ru/uploads/manga/infinity-wars-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"As the Infinity Stones come to Earth, so too comes the war for control over them. But none who wield the stones know the truth about the power they contain\\u2026or what it would take to bring them to their END. The nature of the universe itself hangs in the balance as we learn the answer to the question on everyone\\u2019s lips since \\u201cInfinity Wars Prime\\u201d: WHO IS REQUIEM? Gerry Duggan (DEADPOOL, INFINITY COUNTDOWN) and Mike Deodato Jr. (ORIGINAL SIN, OLD MAN LOGAN) look into the Infinite and bring the truth to light!"}]', '2018-08-03 04:10:29', '2018-08-03 04:11:02'),
(80, 'Ant-Man & The Wasp (2018)', 'http://readcomicsonline.ru/comic/antman-the-wasp-2018', 'http://readcomicsonline.ru/uploads/manga/antman-the-wasp-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"A NEW SERIES FROM MARK WAID & JAVIER GARRON! Wasp was just trying to help Ant-Man get home to Earth to see his daughter...but a little problem got in the way. Very little. Subatomic, in fact, as Scott Lang was lost in the vast spaces between atoms! Now, Nadia is his only hope of rescue\\u2026if only he would listen long enough for her to save them! From master storyteller Mark Waid (CAPTAIN AMERICA, CHAMPIONS) and Marvel Young Gun artist Javier Garr\\u00f3n (SECRET WARRIORS, STAR-LORD) comes a story of a big journey getting smaller all the time!"}]', '2018-08-03 04:10:29', '2018-08-03 04:11:03'),
(81, 'Animosity (2016-)', 'http://readcomicsonline.ru/comic/animosity-2016', 'http://readcomicsonline.ru/uploads/manga/animosity-2016/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"\\u201cThe Animals thought, spoke and took revenge. The dust has settled and the blood has dried, but a new force is rising in the West, ready to help Animal-kind seize power in the dark new world to come\\u2026\\u201d \\r\\n\\r\\nSpinning out from Marguerite Bennett\\u2019s hit new series ANIMOSITY is this special one-shot, illustrated by AMERICAN MONSTER\\u2019s very own Juan Doe! Witness the devastating effects of \\u201cThe Wake\\u201d and how it affected other parts of the world on that terrifying day!"}]', '2018-08-03 04:10:29', '2018-08-03 04:11:03'),
(82, 'Mister Miracle (2017-)', 'http://readcomicsonline.ru/comic/mister-miracle-2017', 'http://readcomicsonline.ru/uploads/manga/mister-miracle-2017/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"From the team behind THE SHERIFF OF BABYLON and the Hugo Award-nominated writer of Vision comes a unique new take on one of Jack Kirby\\u2019s most beloved New Gods.\\r\\n\\r\\n Scott Free is the greatest escape artist that ever lived. So great that he escaped Granny Goodness\\u2019 gruesome orphanage and the dangers of Apokolips to travel across galaxies and set up a new life on Earth with his wife, the former female fury known as Big Barda. Using the stage alter ego of Mister Miracle, he has made a career for himself showing off his acrobatic escape techniques. He even caught the attention of the Justice League, which counted him among its ranks.\\r\\n\\r\\n You might say Scott Free has everything...so why isn\\u2019t it enough? Mister Miracle has mastered every illusion, achieved every stunt, pulled off every trick-except one. He has never escaped death. Is it even possible? Our hero is going to have to kill himself if he wants to find out.\\r\\n\\r\\n Written by Tom King (BATMAN) and illustrated by Mitch Gerads (The Punisher), this is a MISTER MIRACLE unlike any you\\u2019ve read before."}]', '2018-08-03 04:10:29', '2018-08-03 04:11:04'),
(83, 'Death Of The Inhumans (2018)', 'http://readcomicsonline.ru/comic/death-of-the-inhumans-2018', 'http://readcomicsonline.ru/uploads/manga/death-of-the-inhumans-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"THE TITLE SAYS IT ALL \\u2013 HERE LIE THE INHUMANS. The Kree have gone murdering, leaving behind a message: Join or die. Thousands of Inhumans have already made their choice \\u2014 the evidence floats bleeding in space. Black Bolt and his family are next. Rising star Donny Cates and PUNISHER: WAR JOURNAL artist Ariel Olivetti bring their brutal talents to the Inhumans!"}]', '2018-08-03 04:10:29', '2018-08-03 04:11:04'),
(84, 'Cosmic Ghost Rider (2018)', 'http://readcomicsonline.ru/comic/cosmic-ghost-rider-2018', 'http://readcomicsonline.ru/uploads/manga/cosmic-ghost-rider-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"EXPLODING FROM THE PAGES OF THANOS! Frank Castle was the Punisher. A deal with the devil made him Ghost Rider. A deal with Galactus made him cosmic. A deal with Thanos made him\\u2026DEAD?!? Not to worry, he\\u2019s coming back, and he\\u2019s got a plan to make the universe a better place that\\u2019s going to lead him into an even CRAZIER adventure than he\\u2019s ever been in! Join hot new comic (and cosmic?) writer Donny Cates (THANOS, DOCTOR STRANGE) as he pushes his wildest creation past the breaking point!"}]', '2018-08-03 04:10:29', '2018-08-03 04:11:05'),
(85, 'Adventures of the Super Sons (2018-)', 'http://readcomicsonline.ru/comic/adventures-of-the-super-sons-2018', 'http://readcomicsonline.ru/uploads/manga/adventures-of-the-super-sons-2018/cover/cover_250x350.jpg', '[{"raiting":"4.5"},{"summary":"The Super Sons are back in an all-new 12-issue miniseries written by Peter J. Tomasi! Check out the lost and secret adventures of Damian Wayne (Robin) and Jon Kent (Superboy) in this flashback miniseries that takes a deep dive into the bombastic bromance between the sons of the DC Universe\\u2019s greatest heroes. It\\u2019s an epic dual storyline that transcends current events, as Superboy and Robin find themselves targets of an interstellar team of young badasses called the Gang."}]', '2018-08-03 04:10:30', '2018-08-03 04:11:05'),
(86, 'Thief of Thieves (2012-)', 'http://readcomicsonline.ru/comic/thief-of-thieves-2012', 'http://readcomicsonline.ru/uploads/manga/thief-of-thieves-2012/cover/cover_250x350.jpg', '[{"raiting":"4"},{"summary":"Conrad Paulson lives a secret double life as master thief Redmond. There is nothing he can''t steal, nothing he can''t have... except for the life he left behind. Now, with a grown son he hardly knows, and an ex-wife he never stopped loving, Conrad must try to piece together what''s left of his life, before the FBI finally catch up to him... but it appears they are the least of his worries."}]', '2018-08-03 04:10:30', '2018-08-03 04:11:06'),
(87, 'Spawn (1992-)', 'http://readcomicsonline.ru/comic/spawn-1992', 'http://readcomicsonline.ru/uploads/manga/spawn-1992/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"While a strange assailant stalks the city, ripping out human hearts, another otherwordly being arrives. As his mind reels, our tortured hero remembers that he struck a deal with the devil in order to return to his beloved wife - five years after his death."}]', '2018-08-03 04:10:30', '2018-08-03 04:11:06'),
(88, 'Paper Girls (2015-)', 'http://readcomicsonline.ru/comic/paper-girls-2015', 'http://readcomicsonline.ru/uploads/manga/paper-girls-2015/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"SAGA writer BRIAN K. VAUGHAN launches a brand-new ONGOING SERIES with superstar Wonder Woman artist CLIFF CHIANG! In the early hours after Halloween of 1988, four 12-year-old newspaper delivery girls uncover the most important story of all time. Stand By Me meets War of the Worlds in this mysterious young adult adventure, starting with a spectacular DOUBLE-SIZED FIRST ISSUE for the regular price of just $2.99!"}]', '2018-08-03 04:10:31', '2018-08-03 04:11:07'),
(89, 'Star Trek: Discovery: Succession (2018-)', 'http://readcomicsonline.ru/comic/star-trek-discovery-succession-2018', 'http://readcomicsonline.ru/uploads/manga/star-trek-discovery-succession-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"In this, the second Discovery miniseries from IDW Publishing, your favorite characters from the hit CBS All Access series dive into an adventure tied directly into the second half of the first season!"}]', '2018-08-03 04:10:31', '2018-08-03 04:11:07'),
(90, 'Immortal Hulk (2018-)', 'http://readcomicsonline.ru/comic/immortal-hulk-2018', 'http://readcomicsonline.ru/uploads/manga/immortal-hulk-2018/cover/cover_250x350.jpg', '[{"raiting":"4.71"},{"summary":"HORROR HAS A NAME. You''d never notice the man. He doesn''t like to be noticed. He''s quiet. Calm. Never complains. If someone were to walk up and shoot him in the head... all he''d do is die. Until night falls. And someone else gets up again. The man''s name is Banner. The horror is THE IMMORTAL HULK."}]', '2018-08-03 04:10:31', '2018-08-03 04:11:08'),
(91, 'The Unexpected (2018-)', 'http://readcomicsonline.ru/comic/the-unexpected-2018', 'http://readcomicsonline.ru/uploads/manga/the-unexpected-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"In the aftermath of DARK NIGHTS: METAL, the DC Universe has been forever changed as new heroes are called out of the shadows. Amid this all is Janet Fals...Firebrand! Once a paramedic dedicated to saving lives, she must now start a fight once every 24 hours to feed the Conflict Engine that\\u2019s replaced her heart. But Janet\\u2019s heart isn\\u2019t just a curse-it\\u2019s a beacon, drawing out both the mysterious Neon the Unknown and the seductive, malevolent Bad Samaritan. One of them wants to cut out her heart, the other wants to save it-but neither of them knows the true danger hidden within that will kick off a superhero manhunt ranging from Thanagar to the deepest heart of the Dark Multiverse!"}]', '2018-08-03 04:10:31', '2018-08-03 04:11:08'),
(92, 'Nightwing (2016-)', 'http://readcomicsonline.ru/comic/nightwing-2016', 'http://readcomicsonline.ru/uploads/manga/nightwing-2016/cover/cover_250x350.jpg', '[{"raiting":"4.83"},{"summary":"\\"BETTER THAN BATMAN\\" Chapter One\\r\\n\\r\\nBatman taught Nightwing everything he knows\\u2014but what if everything he taught him is wrong? When Dick is stuck with a new mentor who challenges everything Batman taught him, Nightwing has to shatter his concept of justice in order to fight for what he knows is right. Writer Tim Seeley (GRAYSON, BATMAN & ROBIN ETERNAL) launches Nightwing onto a new quest alongside rising talent Javier Fernandez (RED HOOD\\/ARSENAL)."}]', '2018-08-03 04:10:31', '2018-08-03 04:11:09'),
(93, 'IDW Summer Insider 2018', 'http://readcomicsonline.ru/comic/idw-summer-insider-2018', 'http://readcomicsonline.ru/uploads/manga/idw-summer-insider-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"Get an inside look at some of the Fall''s most exciting titles from IDW. Featuring exclusive interviews, previews, and more, get your first look here!"}]', '2018-08-03 04:10:31', '2018-08-03 04:11:09'),
(94, 'Seven To Eternity (2016-)', 'http://readcomicsonline.ru/comic/seven-to-eternity-2016', 'http://readcomicsonline.ru/uploads/manga/seven-to-eternity-2016/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"The God of Whispers has spread an omnipresent paranoia to every corner of the kingdom of Zhal; his spies hide in every hall spreading mistrust and fear. Adam Osidis, a dying knight from a disgraced house, must choose between joining a hopeless band of magic users in their desperat e bid to free their world of the evil God, or accepting his promise to give Adam everything his heart desires. Writer RICK REMENDER reteams with collaborators JEROME OPE\\u00d1A (Uncanny X-Force, Fear Agent) and MATT HOLLINGSWORTH (TOKYO GHOST, WYTCHES) to take you on a hard road through the strange fantasy world of Zhal. All men have surrendered their freedom for fear. Now, one last free man must choose."}]', '2018-08-03 04:10:31', '2018-08-03 04:11:10'),
(95, 'Infinity 8 (2018-)', 'http://readcomicsonline.ru/comic/infinity-8-2018', 'http://readcomicsonline.ru/uploads/manga/infinity-8-2018/cover/cover_250x350.jpg', '[{"raiting":"3.33"},{"summary":"The city-sized, deep-space cruise ship \\"Infinity 8\\" stops halfway en route between the Milky Way and Andromeda, blocked by a massive field of debris containing wreckage and artifacts from countless planets, cultures, and possibly dimensions. The captain of the ship calls upon eight of the ship''s top security to investigate the anomaly, each one sent out in a parallel time-loop to collect information which can then be assembled to hopefully discover the truth before disaster erupts. But danger reveals itself within the interspecies population on the ship, some of whom may know more than they lead on . . . A far-out, pulpy, sci-fi series of parallel adventures by some of the most popular creators in France, in the tongue-in-cheek tradition of the original Heavy Metal but for a new generation. Eight different 3-issue miniseries\\/hardcover collections, all by a different creative team, led by legendary Lewis Trondheim and Olivier Vatine. Part One of the first 3-part arc, \\"Love and Mummies.\\""}]', '2018-08-03 04:10:31', '2018-08-03 04:11:10'),
(96, 'Death of Superman, Part 1 (2018-)', 'http://readcomicsonline.ru/comic/death-of-superman-part-1-2018', 'http://readcomicsonline.ru/uploads/manga/death-of-superman-part-1-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"\\"POWER\\" Part 1! How did Superman miss the beginning of Doomsday''s rampage? Well, first, he had to save Lois Lane''s father from his own folly!"}]', '2018-08-03 04:10:31', '2018-08-03 04:11:11'),
(97, 'Uber Invasion (2016-)', 'http://readcomicsonline.ru/comic/uber-invasion-2016', 'http://readcomicsonline.ru/uploads/manga/uber-invasion-2016/cover/cover_250x350.jpg', '[{"raiting":"4.17"},{"summary":"Kieron Gillen''s reimagining of superpowers and history is back with America under attack! In the waning days of World War II, the Germans discovered a way to enhance soldiers into unstoppable monsters. With these weapons Hitler conquered all of Europe and now has set his sights on the United States. This is Uber: Invasion! The German battleships are on American soil and with the allies struggling to make up lost ground in Enhanced Soldier development; the young country is facing the possibility of annihilation!"}]', '2018-08-03 04:10:32', '2018-08-03 04:11:11'),
(98, 'Scales & Scoundrels (2017)', 'http://readcomicsonline.ru/comic/scales-scoundrels-2017', 'http://readcomicsonline.ru/uploads/manga/scales-scoundrels-2017/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"It''s hard to make an honest living in a land brimming with magic and mystery, and treasure hunter Luvander is tired of being a penniless adventurer. Ever in search of gold and glory, she sets off for a fabled dungeon, \\"the Dragon''s Maw,\\" an ancient labyrinth, at the bottom of which slumbers endless wealth\\u2026or certain doom! But what starts out as a road to riches becomes the first step on an epic journey to destiny, for Luvander holds a secret in her heart that will shatter the chains of fate and bring light to a world encroached upon by an ancient darkness. Writer SEBASTIAN GIRNER (SHIRTLESS BEAR-FIGHTER!) and artist GALAAD are proud to present SCALES & SCOUNDRELS, a colorful and exciting new monthly fantasy adventure from Image Comics, for scoundrels of all ages!"}]', '2018-08-03 04:10:32', '2018-08-03 04:11:12'),
(99, 'Leviathan (2018-)', 'http://readcomicsonline.ru/comic/leviathan-2018', 'http://readcomicsonline.ru/uploads/manga/leviathan-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"Poor Ryan DeLuca didn\\u2019t buy enough beer for his party, and while he was out on a beer run his idiot buddies busted out some mystical arcana and performed a summoning ceremony\\u2014a ceremony that summoned a giant monster from hell! Join multiple Eisner-winning writer JOHN LAYMAN (CHEW) and Eisner-nominated artist NICK PITARRA (THE MANHATTAN PROJECTS), along with soon-to-be-nominated-for-best-colorist MICHAEL GARLAND (THE MANHATTAN PROJECTS) for an eye-popping, face-melting, reality-defying, nonstop rush of pure adrenaline."}]', '2018-08-03 04:10:32', '2018-08-03 04:11:13'),
(100, 'Delta 13 (2018-)', 'http://readcomicsonline.ru/comic/delta-13-2018', 'http://readcomicsonline.ru/uploads/manga/delta-13-2018/cover/cover_250x350.jpg', '[{"raiting":"4"},{"summary":"Who knows what mysteries lie deep in the asteroid belt? When a mysterious, huge, and previously undiscovered asteroid looms over their ship, a small crew of blue-collar workers discovers a terrifying threat unlike anything they''ve ever seen. Now, the crew must escape the asteroid, but even if they do, will they be able to escape each other and anything they bring back with them?"}]', '2018-08-03 04:10:32', '2018-08-03 04:11:13'),
(101, 'DC Nation (2018-)', 'http://readcomicsonline.ru/comic/dc-nation-2018', 'http://readcomicsonline.ru/uploads/manga/dc-nation-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"Just in time for Free Comic Book Day, this special comic features three brand-new stories from a lineup of superstar talent\\u2014and each tale serves as a prelude to some of the biggest DC events of 2018!\\r\\n \\r\\nFirst, find out how The Joker reacts when he discovers Catwoman has turned her back on crime and plans to marry his archnemesis. Can the Clown Prince of Crime stand to see Batman happy? Writer Tom King and artist Clay Mann set up the events that lead to BATMAN #50!\\r\\n \\r\\nThen, DARK NIGHTS: METAL shook the DC Universe to its deepest foundations\\u2014now it\\u2019s time to rejoin legendary writer Scott Snyder, along with all-star artist Jorge Jimenez and co-writers James Tynion IV and Joshua Williamson, for the prelude to JUSTICE LEAGUE: NO JUSTICE! Discover what universe-shattering mysteries have emerged from the most wondrous and chaotic corners of the cosmos to hunt the Justice League in DC\\u2019s summer blockbuster event!\\r\\n \\r\\nPlus, get your first glimpse at Superman\\u2019s new world in this exclusive preview of the upcoming six-issue miniseries MAN OF STEEL, written by Brian Michael Bendis with art by Jos\\u00e9 Luis Garc\\u00eda-L\\u00f3pez. With Truth, Justice and the American Way all under attack, both Superman and Clark Kent find there\\u2019s never been a more important time to stand up for what they believe in."}]', '2018-08-03 04:10:32', '2018-08-03 04:11:14'),
(102, 'Justice League (2018-)', 'http://readcomicsonline.ru/comic/justice-league-2018', 'http://readcomicsonline.ru/uploads/manga/justice-league-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"\\u201cTHE TOTALITY\\u201d part one! A brand-new era begins here! Comics legends Scott Snyder and Jim Cheung launch the Justice League into a cosmos-shaking mystery that will draw out their most terrible foes\\u2026in ways our heroes couldn\\u2019t possibly imagine! In this debut issue, Martian Manhunter struggles to protect the team from an incoming threat that will shatter the world as they know it, while a familiar face strikes out on a dark path\\u2026"}]', '2018-08-03 04:10:32', '2018-08-03 04:11:14'),
(103, 'Green Lanterns  (2016-)', 'http://readcomicsonline.ru/comic/green-lanterns-2016', 'http://readcomicsonline.ru/uploads/manga/green-lanterns-2016/cover/cover_250x350.jpg', '[{"raiting":"4.19"},{"summary":"\\"RED PLANET\\" Chapter One\\r\\n\\r\\nNew Lanterns Jessica Cruz and Simon Baz promised to protect others in brightest day or blackest night, but as \\"Red Planet\\" begins to rise, the partners find themselves confronted with an unimaginable threat from Bleez and the Red Lanterns!\\r\\n\\r\\nTHEY SAID IT: \\"I am psyched for GREEN LANTERNS!\\" says writer Sam Humphries. \\"Myself, Simon, and Jessica are all new to the DC Universe. We''re gonna have a blast exploring it\\u2014if we don''t destroy it first.\\""}]', '2018-08-03 04:10:32', '2018-08-03 04:11:15'),
(104, 'Batman (2016-)', 'http://readcomicsonline.ru/comic/batman-2016', 'http://readcomicsonline.ru/uploads/manga/batman-2016/cover/cover_250x350.jpg', '[{"raiting":"4.45"},{"summary":"\\"I AM GOTHAM\\" Chapter One\\r\\n\\r\\nNo one has ever stopped the Caped Crusader. Not The Joker. Not Two-Face. Not even the entire Justice League. But how does Batman confront a new hero who wants to save the city from the Dark Knight?\\r\\n\\r\\nCAN''T MISS: Superstar artist David Finch returns to Batman alongside writer Tom King for this five-part storyline."}]', '2018-08-03 04:10:33', '2018-08-03 04:11:16'),
(105, '2000 AD', 'http://readcomicsonline.ru/comic/2000-ad', 'http://readcomicsonline.ru/uploads/manga/2000-ad/cover/cover_250x350.jpg', '[{"raiting":"4"},{"summary":"Iconic, cult and British aptly describe 2000 AD. For over 35 years it has delivered weekly thrill-power to the masses. Much of its success lies in its consistency, as original creators Pat Mills and John Wagner still write for the comic and future lawman Judge Dredd has been at the core of the sci-fi anthology since prog 2. As well as appearing in the weekly, Dredd''s popularity has granted him his own series, which is still going today having topped 350+ issues as well as appearances in Annuals (1980-1990), Yearbooks (1991-1994) and Mega-Specials (1988-1996). For any previous issues can be downloaded at http:\\/\\/getcomics.info\\/?s=2000AD"}]', '2018-08-03 04:10:33', '2018-08-03 04:11:16'),
(106, 'Injustice 2 (2017-)', 'http://readcomicsonline.ru/comic/injustice-2-2017', 'http://readcomicsonline.ru/uploads/manga/injustice-2-2017/cover/cover_250x350.jpg', '[{"raiting":"4.33"},{"summary":"The all-new prequel to the highly anticipated Injustice 2 video game begins here! Original INJUSTICE writer Tom Taylor continues the story from the hit series INJUSTICE: GODS AMONG US. Superman is imprisoned, and it\\u2019s up to Batman to put the world back together. But with Superman\\u2019s iron-fisted regime eliminated, other forces rise up to fill the void. And Batman doesn\\u2019t have a lot of allies left to help stop them."}]', '2018-08-03 04:10:33', '2018-08-03 04:11:17'),
(107, 'Jughead: the Hunger (2017)', 'http://readcomicsonline.ru/comic/jughead-the-hunger-2017', 'http://readcomicsonline.ru/uploads/manga/jughead-the-hunger-2017/cover/cover_250x350.jpg', '[{"raiting":"4.33"},{"summary":"BRAND NEW ONE-SHOT SPECIAL! Jughead Jones has always had an insatiable appetite... but what if his hunger came from a sinister place? When a murderous menace is on the prowl, taking the lives of some of the most well-known and esteemed inhabitants of Riverdale, Jughead and his family''s dark legacy comes to light. Join writer Frank Tieri (Wolverine) and artist Michael Walsh (Secret Avengers) for this horrifying one-shot for TEEN+ readers."}]', '2018-08-03 04:10:33', '2018-08-03 04:11:18'),
(108, 'Betty & Veronica: Vixens (2017)', 'http://readcomicsonline.ru/comic/betty-veronica-vixens-2017', 'http://readcomicsonline.ru/uploads/manga/betty-veronica-vixens-2017/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"NEW ONGOING SERIES! The toughest gang in Riverdale is one you''d least expect: the Vixens, led by Riverdale High''s own Betty and Veronica!"}]', '2018-08-03 04:10:33', '2018-08-03 04:11:18'),
(109, 'Scooby-Doo! Team-Up (2013)', 'http://readcomicsonline.ru/comic/scoobydoo-teamup-2013', 'http://readcomicsonline.ru/uploads/manga/scoobydoo-teamup-2013/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"Digital chapters for the print Scooby-Doo Team-Up series, each print issue is two digital chapters. Issue #1 - 27 can be downloaded on http:\\/\\/getcomics.info\\/dc\\/scooby-doo-team-up-1-27\\/"}]', '2018-08-03 04:10:33', '2018-08-03 04:11:19'),
(110, 'Executive Assistant: Iris Vol. 5 (2018-)', 'http://readcomicsonline.ru/comic/executive-assistant-iris-vol-5-2018', 'http://readcomicsonline.ru/uploads/manga/executive-assistant-iris-vol-5-2018/cover/cover_250x350.jpg', '[{"raiting":"3"},{"summary":"Aspen Comics\\u2019 hit action-adventure assassin series marks its 10-Year Anniversary with a brand new pulse-pounding volume! When a routine security job takes a turn for the worse, Executive Assistant Iris realizes she might be at the crossroads of her career! The world\\u2019s deadliest assassin is faced with a choice: remain a freelance Executive Assistant, or join Magni Global\\u2014a mysterious corporation that has acquired nearly every private security firm on the planet. But, what fateful decisions may come from joining a giant conglomerate whose interests may spell doom for her?! Brought to you by acclaimed author Blake Northcott (Michael Turner\\u2019s Fathom) with art by newcomer Donny Tran and colorist Luis Guerrero, this newest pulse-pounding 10 year anniversary chapter of Executive Assistant: Iris is sure to be the greatest volume yet!"}]', '2018-08-03 04:10:33', '2018-08-03 04:11:19'),
(111, 'Dissension War Enteral (2018-)', 'http://readcomicsonline.ru/comic/dissension-war-enteral-2018', 'http://readcomicsonline.ru/uploads/manga/dissension-war-enteral-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"In the not so distant future\\u2026 The U.S. has spent several years embroiled in a conflict with the invading forces of China. In the war zone of the American Southwest, small bands of freedom fighters have formed to help guide refugees away from the destruction. Isabel Vasquez, known to her squad as \\"Delphi\\", has been leading rescue missions inside the combat zone for years. Escorting those displaced from the war has fueled her faith that she is making a difference. But now that faith is increasingly tested by reoccurring nightmares of a coming apocalypse. She fears the war is only the beginning of a great threat\\u2026one that promises to bring humanity to the brink of extinction! Unbeknownst to Delphi, a band of renegade angels has fled Heaven seeking a new refuge. The Earth has become their new home, where they view humanity as a plague that must be purged. As their path forges ahead toward global genocide, it is yet to be decided if Delphi and her growing visions of a global Armageddon can help stop them in time. From artist and creator Jordan Gunderson comes Aspen\\u2019s most thrilling new series of the summer, DISSENSION: WAR ETERNAL!"}]', '2018-08-03 04:10:33', '2018-08-03 04:11:20'),
(112, 'Vampblade Season 3 (2018-)', 'http://readcomicsonline.ru/comic/vampblade-season-3-2018', 'http://readcomicsonline.ru/uploads/manga/vampblade-season-3-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"Other-dimensional vampire slaying comic shop owner Katie Carva literally reboots when the Vampblades transplant an alternate dimension version of Detroit to replace her recently destroyed city! Now Katie must survive the Glarkian space vampire invasion all over again\\u2026 PLUS deal with a second version of herself that came along for the ride!! It\\u2019s double the Vampblade, double the fun!"}]', '2018-08-03 04:10:34', '2018-08-03 04:11:20'),
(113, 'Rick and Morty (2015-)', 'http://readcomicsonline.ru/comic/rick-and-morty-2015', 'http://readcomicsonline.ru/uploads/manga/rick-and-morty-2015/cover/cover_250x350.jpg', '[{"raiting":"4.29"},{"summary":"Comic based on the [adult swim] animated series Rick and Morty created by Justin Roiland and Dan Harmon."}]', '2018-08-03 04:10:34', '2018-08-03 04:11:21'),
(114, 'Pestilence: A Story of Satan (2018-)', 'http://readcomicsonline.ru/comic/pestilence-a-story-of-satan-2018', 'http://readcomicsonline.ru/uploads/manga/pestilence-a-story-of-satan-2018/cover/cover_250x350.jpg', '[{"raiting":"0"},{"summary":"The second volume of this hit AfterShock series starts here!\\r\\n\\r\\nThe year is 1353. The fugitive Roderick Helms has retreated to a life of hidden seclusion after failing to expose the Church''s role in the Black Death. But something threatens to bring him back into action. Something that has risen which will threaten to transform the waning plague into a far more darker and sinister crisis. And that something is none other than Satan himself!"}]', '2018-08-03 04:10:34', '2018-08-03 04:11:21'),
(115, 'Night''s Dominion: Season Three (2018-)', 'http://readcomicsonline.ru/comic/nights-dominion-season-three-2018', 'http://readcomicsonline.ru/uploads/manga/nights-dominion-season-three-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"As poison slowly claims the Furie, Emerane attempts the unthinkable. With the help of the Magus''s necromancy, she infiltrates the dominion of death itself. If all goes well, Emerane may be able to rescue the Furie''s soul from the shores of oblivion. But if she fails, she will be claimed by Uhlume, the god of death."}]', '2018-08-03 04:10:34', '2018-08-03 04:11:22'),
(116, 'Moonshine (2016-)', 'http://readcomicsonline.ru/comic/moonshine-2016', 'http://readcomicsonline.ru/uploads/manga/moonshine-2016/cover/cover_250x350.jpg', '[{"raiting":"3.67"},{"summary":"Set during Prohibition, and deep in the backwoods of Appalachia, MOONSHINE #1 tells the story of Lou Pirlo, a city-slick \\"torpedo\\" sent from New York City to negotiate a deal with the best moonshiner in West Virginia, one Hiram Holt. What Lou doesn''t figure on is that Holt is just as cunning and ruthless as any NYC crime boss. Because not only will Holt do anything to protect his illicit booze operation, he''ll stop at nothing to protect a much darker family secret...a bloody, supernatural secret that must never see the light of day... or better still, the light of the full moon. MOONSHINE #1 marks the first time AZZARELLO and RISSO have worked together for Image Comics and reunites the Eisner Award winning creative team that defined modern crime comics with 100 Bullets... and now puts a horror-twist on a classic gangster tale. Issue #1 features a variant cover by legendary comics creator, Frank Miller!"}]', '2018-08-03 04:10:34', '2018-08-03 04:11:22'),
(117, 'Danger Doll Squad: Galactic Gladiators (2018-)', 'http://readcomicsonline.ru/comic/danger-doll-squad-galactic-gladiators-2018', 'http://readcomicsonline.ru/uploads/manga/danger-doll-squad-galactic-gladiators-2018/cover/cover_250x350.jpg', '[{"raiting":"2"},{"summary":"The popular Danger Zone team-up event series returns!! Zombie Tramp, Vampblade, and DollFace come together again, and this time they\\u2019re forced into battle\\u2026 in space! When a new cosmic threat plucks the girls from Earth and places them into their galactic combat arena, can our lethal ladies measure up against the baddest gladiators from across the cosmos??"}]', '2018-08-03 04:10:34', '2018-08-03 04:11:23'),
(118, 'Wayward (2014-)', 'http://readcomicsonline.ru/comic/wayward-2014', 'http://readcomicsonline.ru/uploads/manga/wayward-2014/cover/cover_250x350.jpg', '[{"raiting":"2.56"},{"summary":"BUFFY THE VAMPIRE SLAYER FOR A NEW GENERATION! Rori Lane is trying to start a new life when she reunites with her mother in Japan, but ancient creatures lurking in the shadows of Tokyo sense something hidden deep within her, threatening everything she holds dear. Can Rori unlock the secrets of her power before it''s too late? JIM ZUB (SKULLKICKERS, Samurai Jack), STEVE CUMMINGS (Legends of the Dark Knight, Deadshot), and JOHN RAUCH (INVINCIBLE) team up to create an all-new Image supernatural spectacle that combines the camaraderie and emotion of Buffy the Vampire Slayer with the action and mystery of Hellboy. Don''t miss it!"}]', '2018-08-03 04:10:34', '2018-08-03 04:11:23'),
(119, 'Teenage Mutant Ninja Turtles (2011-)', 'http://readcomicsonline.ru/comic/teenage-mutant-ninja-turtles-2011', 'http://readcomicsonline.ru/uploads/manga/teenage-mutant-ninja-turtles-2011/cover/cover_250x350.jpg', '[{"raiting":"4.6"},{"summary":"They''re BACK! This summer, the original heroes in a half-shell make a triumphant return to comics! Leonardo, Donatello, Michaelangelo, and Raphael reunite to bring their ninja aptitude and teenage attitude to IDW Publishing in this all-new, action-packed series."}]', '2018-08-03 04:10:34', '2018-08-03 04:11:24'),
(120, 'Mera: Queen of Atlantis (2018-)', 'http://readcomicsonline.ru/comic/mera-queen-of-atlantis-2018', 'http://readcomicsonline.ru/uploads/manga/mera-queen-of-atlantis-2018/cover/cover_250x350.jpg', '[{"raiting":"5"},{"summary":"From the pages of AQUAMAN comes a brand-new adventure starring Mera, in her own title for the first time ever! \\r\\nAs the brutal Atlantean Civil War rages, Mera must keep the peace between the surface world and Atlantis as its newly anointed queen in exile. But when Aquaman\\u2019s brother Orm, a.k.a. Ocean Master, learns of his homeland\\u2019s fate, he\\u2019ll stop at nothing to return to Atlantis as its king and savior!"}]', '2018-08-03 04:10:34', '2018-08-03 04:11:25');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(161) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(161) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(161) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci AUTO_INCREMENT=1 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
